apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: navneet0709/task-manager-ssl:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 443
#            scheme: HTTPS
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 443
#            scheme: HTTPS
#          initialDelaySeconds: 15
#          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 32000
